import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       
      <main className={styles.main}>
        <h1 className={styles.title}>
        Hunting Coder
        </h1>
        <div className={styles.imagewrap}>
        <Image className={styles.myimg} src={'/home2.jpg'} width={'500'} height={'300'}/>
        </div>
        <p className={styles.description}>
          A blog for hunting coder by a hunting coders
        </p>


        <div className={styles.blogs}>
        <h1>Poppular Blogs</h1>

        <div className={styles.grid}>
          {/* <a href="#" className={`${styles.card} ${styles.blogitems}`}> */}
          <Link href={"/blogpost/How to learn javascript"}><a href="#" className={styles.card}>
            <h2>How to learn javascript in 2022 &rarr;</h2>
            <p>Javascript is a language used to design logic for a web.</p>
          </a></Link>

          <Link href={"/blogpost/How to learn javascript"}><a href="#" className={styles.card}>
            <h2>How to learn javascript in 2022 &rarr;</h2>
            <p>Javascript is a language used to design logic for a web.</p>
          </a></Link>
          <Link href={"/blogpost/How to learn javascript"}><a href="#" className={styles.card}>
            <h2>How to learn javascript in 2022 &rarr;</h2>
            <p>Javascript is a language used to design logic for a web.</p>
          </a></Link>

          <Link href={"/blogpost/Learning-JS"}><a href="#" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a></Link>

        </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
